# Generated by Django 4.0.1 on 2022-01-11 10:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MNRNetwGeoLink',
            fields=[
                ('feat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ft_road_element', models.BooleanField()),
                ('ft_ferry_element', models.BooleanField()),
                ('ft_address_element', models.BooleanField()),
                ('country_left', models.CharField(max_length=3)),
                ('country_right', models.CharField(max_length=3)),
                ('centimeters', models.IntegerField()),
                ('positional_accuracy', models.IntegerField(choices=[(1, 'Good'), (2, 'Medium'), (3, 'Bad')])),
                ('ada_compliant', models.BooleanField()),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
        ),
    ]
