# Generated by Django 4.0.1 on 2022-02-05 19:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerCarRestrictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_freeway', models.BooleanField()),
                ('road_type', models.IntegerField()),
                ('speed_limitations', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='MNRNetwGeoLink',
        ),
    ]
